FROM elixir:latest

RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

COPY config/prod.secret.exs config/prod.secret.exs
COPY mix.exs mix.lock ./
COPY config config

# COPY --from=build /app/priv/static priv/static

RUN mix do deps.get, deps.compile

COPY lib lib
COPY priv priv

EXPOSE 8080

CMD ["mix", "phx.server"]
