version: '3.8'

services:
  phoenix_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      MIX_ENV: dev
  # db:
  #   image: postgres
  #   container_name: elixir-ipsum-db
  #   environment:
  #       POSTGRES_PASSWORD: root
  #       POSTGRES_DB: elixir_ipsum
  #   volumes:
  #     - db-data:/var/lib/postgresql/data 
  #   ports:
  #     - 5432:5432