# fly.toml app configuration file generated for elixir-ipsum on 2023-12-23T12:18:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elixir-ipsum"
primary_region = "sea"

[env]
  PHX_HOST = "elixir-ipsum.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  processes = ["app"]
